const memory=new Map(),pending=new Map();
const mapping={piano:'piano',epiano:'epiano',guitar:'guitar',strings:'strings',pad:'strings',bass:'bass'};
export const sampleStats={loaded:0,played:0};
const midi=name=>{const m=/^([A-G])(b|#)?(\d)$/.exec(name),pc={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1]]+(m[2]==='b'?-1:m[2]==='#'?1:0);return 12*(Number(m[3])+1)+pc;};
export async function loadSamples(context,fetcher=fetch){
 await Promise.all(['piano','epiano','guitar','bass','strings','drums'].map(async bank=>{if(memory.has(bank))return;if(!pending.has(bank))pending.set(bank,(async()=>{const r=await fetcher('/remix/samples/'+bank+'.json?v=1');if(!r.ok)throw Error('Не удалось загрузить звуки. Проверь соединение и повтори.');const data=await r.json(),notes=await Promise.all(Object.entries(data.notes).map(async([name,encoded])=>{const raw=atob(encoded),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0)),buffer=await context.decodeAudioData(bytes.buffer);return {midi:midi(name),buffer};}));memory.set(bank,notes);sampleStats.loaded+=notes.length;})().finally(()=>pending.delete(bank)));await pending.get(bank);}));
}
export function sampleNote(c,out,instrument,pitch,when,duration,level){const bank=mapping[instrument]||instrument,notes=memory.get(bank);if(!notes)return false;const nearest=notes.reduce((a,b)=>Math.abs(a.midi-pitch)<Math.abs(b.midi-pitch)?a:b),source=c.createBufferSource(),gain=c.createGain(),pan=c.createStereoPanner();source.buffer=nearest.buffer;source.playbackRate.value=2**((pitch-nearest.midi)/12);const length=Math.min(duration,source.buffer.duration/source.playbackRate.value-.02);if(length<=.01)return false;const attack=bank==='strings'?.07:.006,release=Math.min(.18,length*.25),peak=Math.max(.0001,level);gain.gain.setValueAtTime(.0001,when);gain.gain.linearRampToValueAtTime(peak,when+Math.min(attack,length*.25));gain.gain.setValueAtTime(peak,when+Math.max(attack,length-release));gain.gain.exponentialRampToValueAtTime(.0001,when+length);pan.pan.value=bank==='drums'?0:bank==='bass'?0:Math.sin(pitch*.9)*.18;source.connect(gain).connect(pan).connect(out);source.start(when);source.stop(when+length+.01);source.onended=()=>{source.disconnect();gain.disconnect();pan.disconnect();};sampleStats.played++;return true;}
export function sampleDrum(c,out,index,when,level){const pitches={0:36,1:38,2:39,3:42,4:46,6:41},pitch=pitches[index];if(pitch===undefined)return false;return sampleNote(c,out,'drums',pitch,when,index===4?.4:.24,level*.6);}
// Carry sample attribution inside downloaded WAVs without altering their PCM data.
export function attachSampleCredits(bytes){const text=new TextEncoder().encode('FluidR3_GM samples: Frank Wen, Josh Green, S. Christian Collins and contributors. MP3 conversions: gleitz/midi-js-soundfonts; drum subset: dave4mpls/midi-js-soundfonts-with-drums. CC BY 3.0 US https://creativecommons.org/licenses/by/3.0/us/; selected, pitch shifted and enveloped by ANDATRA.\0'),size=text.length+(text.length%2),extra=20+size,out=new Uint8Array(bytes.byteLength+extra);out.set(new Uint8Array(bytes));const v=new DataView(out.buffer),at=bytes.byteLength;const str=(offset,s)=>[...s].forEach((x,i)=>v.setUint8(offset+i,x.charCodeAt(0)));str(at,'LIST');v.setUint32(at+4,extra-8,true);str(at+8,'INFO');str(at+12,'ICMT');v.setUint32(at+16,text.length,true);out.set(text,at+20);v.setUint32(4,out.length-8,true);return out.buffer;}
