const $=id=>document.getElementById(id);
let generation=0, transferred=false;
let file,worker,busy=false,beatBlob,voiceBlob,urls=[],baseName='трек';
const status=(text,error=false)=>{$('status').textContent=text;$('status').classList.toggle('error',error);};
function lock(value){busy=value;$('file').disabled=value;$('scope').disabled=value;$('run').disabled=value||!file;$('cancel').hidden=!value;}
function clearResults(){for(const audio of [$('vocals'),$('instrumental')]){audio.pause();audio.removeAttribute('src');audio.load();}urls.forEach(URL.revokeObjectURL);urls=[];beatBlob=voiceBlob=undefined;$('results').hidden=true;}
export function wav(channels,rate){const count=channels.length,frames=channels[0].length;const bytes=new ArrayBuffer(44+frames*count*2),v=new DataView(bytes);const text=(at,s)=>[...s].forEach((c,i)=>v.setUint8(at+i,c.charCodeAt(0)));text(0,'RIFF');v.setUint32(4,bytes.byteLength-8,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,count,true);v.setUint32(24,rate,true);v.setUint32(28,rate*count*2,true);v.setUint16(32,count*2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,frames*count*2,true);let at=44;for(let i=0;i<frames;i++)for(const samples of channels){const s=Math.max(-1,Math.min(1,samples[i]||0));v.setInt16(at,Math.round(s*(s<0?32768:32767)),true);at+=2;}return new Blob([bytes],{type:'audio/wav'});}
function show(data){beatBlob=wav(data.instrumental,data.sampleRate);voiceBlob=wav(data.vocals,data.sampleRate);for(const [id,blob]of [['instrumental',beatBlob],['vocals',voiceBlob]]){const url=URL.createObjectURL(blob);urls.push(url);$(id).src=url;}$('results').hidden=false;$('progress').value=1;status('Готово. Прослушай минус и голос, затем скачай результат.');lock(false);worker.terminate();worker=undefined;}
function fail(message){worker?.terminate();worker=undefined;lock(false);$('progress').hidden=true;status(message,true);}
function makeWorker(){const w=new Worker('/separate/engine.js?v=istft-3',{type:'module'});w.onmessage=({data})=>{if(w!==worker)return;if(data.type==='status'){status(data.text);$('progress').removeAttribute('value');}if(data.type==='download'){$('progress').value=Math.min(1,data.loaded/data.total);status(`Загружаю модель: ${Math.round(data.loaded/1048576)} МБ…`);}if(data.type==='progress'){$('progress').value=data.step/data.total;status(`Отделяю голос: ${data.step} из ${data.total} фрагментов. Оставь вкладку открытой.`);}if(data.type==='done')show(data);if(data.type==='error')fail('Не удалось обработать: '+data.message+' Попробуй короткий фрагмент в Chrome или Edge.');};w.onerror=()=>fail('Не удалось запустить обработку. Проверь интернет и попробуй Chrome или Edge на компьютере.');return w;}
$('file').onchange=()=>{file=$('file').files[0];$('run').disabled=!file;$('filename').textContent=file?file.name:'Песня не выбрана';status(file?'Можно начать обработку.':'Выбери песню для обработки.');};
$('run').onclick=async()=>{if(!file||busy)return;const token=++generation;lock(true);clearResults();$('progress').hidden=false;$('progress').removeAttribute('value');status('Читаю песню…');baseName=file.name.replace(/\.[^.]+$/,'');let context;
try{if(file.size>100*1024*1024)throw Error('Файл больше 100 МБ.');context=new AudioContext({sampleRate:44100});const decoded=await context.decodeAudioData(await file.arrayBuffer());if(!busy||token!==generation)return;const full=$('scope').value==='full';if(full&&decoded.duration>300)throw Error('Для первого варианта поддерживаются треки до 5 минут. Выбери пробу на 30 секунд.');const frames=Math.min(decoded.length,Math.floor((full?300:30)*decoded.sampleRate));if(!frames)throw Error('Файл не содержит звука.');const offline=new OfflineAudioContext(2,Math.ceil(frames*44100/decoded.sampleRate),44100),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const rendered=await offline.startRendering();if(!busy||token!==generation)return;const channelData=[new Float32Array(rendered.getChannelData(0)),new Float32Array(rendered.getChannelData(Math.min(1,decoded.numberOfChannels-1)))];worker=makeWorker();worker.postMessage({audio:{channelData,sampleRate:44100}},channelData.map(c=>c.buffer));}catch(error){if(token!==generation)return;fail(error.message||'Не удалось прочитать аудиофайл.');}finally{await context?.close();}};
$('cancel').onclick=()=>{generation++;worker?.terminate();worker=undefined;lock(false);$('progress').hidden=true;status('Обработка остановлена. Можно выбрать другую песню.');};
function download(blob,suffix){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=baseName+suffix+'.wav';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('saveBeat').onclick=()=>download(beatBlob,' — минус');$('saveVoice').onclick=()=>download(voiceBlob,' — голос');
$('toStudio').onclick=async()=>{const button=$('toStudio');button.disabled=true;try{await new Promise((resolve,reject)=>{const request=indexedDB.open('andatra-audio-transfer',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('files','readwrite');tx.objectStore('files').put({blob:beatBlob,name:baseName+' — минус.wav'},'beat');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};};});transferred=true;location.href='/studio.html?import=separated';}catch{status('Не удалось передать минус. Скачай WAV и загрузи его в студии.',true);}finally{button.disabled=false;}};
$('gpu').textContent=navigator.gpu?'Для ускорения будет использована видеокарта, если браузер её поддерживает.':'В этом браузере нет WebGPU. Обработка на процессоре может занять значительно больше времени.';
for(const id of ['instrumental','vocals'])$(id).onplay=()=>$(id==='vocals'?'instrumental':'vocals').pause();
window.addEventListener('beforeunload',event=>{if(!transferred&&(busy||beatBlob)){event.preventDefault();event.returnValue='';}});
