import {catalog,genres,instruments,melodyConfig,scheduleMelody} from './melodies.js?v=3';
import {voices,stepTime,validateProject,bus,trigger,wav} from './audio.js?v=3';
const $=id=>document.getElementById(id),blank=()=>voices.map(()=>Array(16).fill(0)),key='andatra-beat-maker-v2';
let project={version:2,melodies:Array.from({length:4},()=>melodyConfig()),patterns:Array.from({length:4},blank),bpm:100,swing:0,kit:'classic',volume:.8,mix:Array(8).fill(1),muted:Array(8).fill(false)};
try{const saved=localStorage.getItem(key);if(saved)project=validateProject(JSON.parse(saved));}catch{}
let selected=0,active=0,pendingPattern=null,context,master,playing=false,recording=false,metro=false,timer,nextTime=0,step=0,timeline=[],scheduled=[],tapTimes=[],exporting=false,uiStep=-1,barIndex=-1,previewNodes=[],previewTimer;
const status=(s,error=false)=>{$('status').textContent=s;$('status').classList.toggle('error',error);};
function persist(){try{localStorage.setItem(key,JSON.stringify(project));}catch{status('Не удалось сохранить в браузере. Скачай проект файлом.',true);}}
async function audio(){if(!context){context=new AudioContext({latencyHint:'interactive'});master=bus(context,context.destination,project.volume);}if(context.state!=='running')await context.resume();return context;}
function flash(i){const pad=$('pads').children[i];pad.classList.add('hit');setTimeout(()=>pad.classList.remove('hit'),90);}
async function hit(i){try{await audio();trigger(context,master,i,context.currentTime,Number($('velocity').value)*project.mix[i],project.kit);flash(i);if(recording&&playing){const time=context.currentTime;let nearest=timeline.reduce((best,e)=>Math.abs(e.time-time)<Math.abs(best.time-time)?e:best,{time:nextTime,step,pattern:active});project.patterns[nearest.pattern][i][nearest.step]=Number($('velocity').value);if(selected===nearest.pattern)renderGrid();persist();}}catch(e){status('Не удалось включить звук: '+e.message,true);}}
voices.forEach(([name,letter],i)=>{const pad=document.createElement('button');pad.className='pad';pad.innerHTML=name+'<small>'+letter+'</small>';pad.onpointerdown=e=>{e.preventDefault();hit(i);};pad.onclick=e=>{if(e.detail===0)hit(i);};$('pads').append(pad);const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='range';input.min=0;input.max=100;input.value=project.mix[i]*100;input.setAttribute('aria-label','Громкость '+name);input.oninput=()=>{project.mix[i]=Number(input.value)/100;persist();};label.append(input);$('mixer').append(label);});
function renderTabs(){[...$('patterns').children].forEach((button,i)=>{button.setAttribute('aria-pressed',String(i===selected));button.textContent='ABCD'[i]+(playing&&active===i?' · ▶':'');});}
for(let i=0;i<4;i++){const button=document.createElement('button');button.textContent='ABCD'[i];button.onclick=()=>{selected=i;if(playing&&!$('chain').checked){pendingPattern=i;status('Паттерн '+button.textContent[0]+' включится со следующего такта.');}else if(!playing)active=i;renderTabs();renderGrid();syncMelody();};$('patterns').append(button);}
function renderGrid(){const root=$('grid');root.replaceChildren();root.append(document.createElement('div'));for(let s=0;s<16;s++){const num=document.createElement('div');num.className='step-num';num.textContent=s%4===0?String(s/4+1):'·';root.append(num);}voices.forEach(([name],i)=>{const label=document.createElement('div');label.className='row-label';const title=document.createElement('span');title.textContent=name;const mute=document.createElement('button');mute.className='mute';mute.textContent=project.muted[i]?'OFF':'ON';mute.setAttribute('aria-label',(project.muted[i]?'Включить ':'Отключить ')+name);mute.setAttribute('aria-pressed',String(project.muted[i]));mute.onclick=()=>{project.muted[i]=!project.muted[i];persist();renderGrid();};label.append(title,mute);root.append(label);for(let s=0;s<16;s++){const button=document.createElement('button'),v=project.patterns[selected][i][s];button.className='step'+(s%4===0?' beat':'')+(v?' active':'');button.dataset.step=s;button.style.setProperty('--velocity',v?Math.max(.4,v):1);button.setAttribute('aria-label',`${name}, шаг ${s+1}, ${v?Math.round(v*100)+'%':'выключен'}`);button.setAttribute('aria-pressed',String(v>0));button.onclick=()=>{const force=Number($('velocity').value);project.patterns[selected][i][s]=v===force?0:force;persist();renderGrid();};root.append(button);}});uiStep=-1;}
function click(when){const o=context.createOscillator(),g=context.createGain();o.frequency.value=1000;g.gain.setValueAtTime(.1,when);g.gain.exponentialRampToValueAtTime(.001,when+.025);o.connect(g).connect(master);o.start(when);o.stop(when+.03);scheduled.push({end:when+.1,nodes:[o,g]});}
function scheduler(){if(!playing)return;const now=context.currentTime;scheduled=scheduled.filter(item=>{if(item.end>now)return true;item.nodes.forEach(n=>{try{n.disconnect();}catch{}});return false;});while(nextTime<now+.12){if(step===0){barIndex++;if(pendingPattern!==null){active=pendingPattern;pendingPattern=null;}else if(barIndex>0&&$('chain').checked)active=(active+1)%4;}timeline.push({time:nextTime,step,pattern:active});voices.forEach((_,i)=>{const velocity=project.patterns[active][i][step];if(velocity&&!project.muted[i])scheduled.push({end:nextTime+1.5,nodes:trigger(context,master,i,nextTime,velocity*project.mix[i],project.kit)});});scheduled.push(...scheduleMelody(context,master,project.melodies[active],barIndex,step,nextTime,project.bpm));if(metro&&step%4===0)click(nextTime);const current=step;step=(step+1)%16;nextTime+=stepTime(current+1,project.bpm,project.swing)-stepTime(current,project.bpm,project.swing);}timeline=timeline.filter(e=>e.time>now-.25);}
async function play(){try{await audio();if(playing){stop();return;}stopPreview();playing=true;active=selected;step=0;barIndex=-1;timeline=[];nextTime=context.currentTime+.05;$('play').textContent='■ Стоп';scheduler();timer=setInterval(scheduler,25);renderTabs();status(recording?'Запись: играй на пэдах. Удары привязываются к сетке.':'Ритм играет. Меняй шаги и звуки в процессе.');}catch(e){status(e.message,true);}}
function stop(){stopPreview();playing=false;recording=false;clearInterval(timer);for(const item of scheduled)item.nodes.forEach(n=>{try{n.stop?.();}catch{}try{n.disconnect();}catch{}});scheduled=[];timeline=[];pendingPattern=null;$('play').textContent='▶ Играть';$('record').classList.remove('on');$('record').textContent='● Запись с пэдов';$('position').textContent='01 / 16';renderTabs();document.querySelectorAll('.current').forEach(e=>e.classList.remove('current'));uiStep=-1;}
$('play').onclick=play;$('record').onclick=async()=>{recording=!recording;if(recording&&!playing){await play();if(!playing){recording=false;return;}}$('record').classList.toggle('on',recording);$('record').textContent=recording?'■ Закончить запись':'● Запись с пэдов';status(recording?'Запись с пэдов: удары добавляются в паттерн.':'Запись завершена. Паттерн продолжает играть.');};
$('metronome').onclick=()=>{metro=!metro;$('metronome').setAttribute('aria-pressed',String(metro));$('metronome').classList.toggle('on',metro);};
function sync(){for(const[id,value]of [['bpm',project.bpm],['swing',project.swing*100],['volume',project.volume*100],['kit',project.kit]])$(id).value=value;$('swingOut').textContent=Math.round(project.swing*100)+'%';[...$('mixer').querySelectorAll('input')].forEach((input,i)=>input.value=project.mix[i]*100);if(master)master.gain.value=project.volume;renderTabs();renderGrid();syncMelody();}
$('bpm').onchange=()=>{project.bpm=Math.max(40,Math.min(240,Number($('bpm').value)||100));$('bpm').value=project.bpm;persist();};$('swing').oninput=()=>{project.swing=Number($('swing').value)/100;$('swingOut').textContent=$('swing').value+'%';persist();};$('kit').onchange=()=>{project.kit=$('kit').value;persist();};$('volume').oninput=()=>{project.volume=Number($('volume').value)/100;if(master)master.gain.value=project.volume;persist();};
$('tap').onclick=()=>{const now=performance.now();if(tapTimes.length&&now-tapTimes.at(-1)>2000)tapTimes=[];if(tapTimes.length&&now-tapTimes.at(-1)<100)return;tapTimes.push(now);tapTimes=tapTimes.slice(-9);if(tapTimes.length<3){status('Tap: нажми ещё несколько раз в такт.');return;}const intervals=tapTimes.slice(1).map((t,i)=>t-tapTimes[i]).sort((a,b)=>a-b),middle=intervals[Math.floor(intervals.length/2)];project.bpm=Math.max(40,Math.min(240,Math.round(60000/middle)));$('bpm').value=project.bpm;persist();status('Темп: '+project.bpm+' BPM.');};
$('copy').onclick=()=>{const target=(selected+1)%4;project.patterns[target]=project.patterns[selected].map(r=>r.slice());project.melodies[target]={...project.melodies[selected]};persist();status('Паттерн '+ 'ABCD'[selected]+' скопирован в '+ 'ABCD'[target]+'.');};$('clear').onclick=()=>{if(confirm('Очистить паттерн '+ 'ABCD'[selected]+'?')){project.patterns[selected]=blank();project.melodies[selected].enabled=false;persist();renderGrid();syncMelody();}};
const presets={boom:{bpm:90,kit:'classic',rows:[[0,6,8,14],[4,12],[],[0,2,4,6,8,10,12,14],[],[0,8],[],[10]]},trap:{bpm:140,kit:'trap',rows:[[0,7,10],[4,12],[4,12],[0,2,4,6,7,8,10,12,14,15],[11],[0,7,10],[],[]]},house:{bpm:124,kit:'electro',rows:[[0,4,8,12],[],[4,12],[2,6,10,14],[2,6,10,14],[0,8],[],[]]},break:{bpm:110,kit:'classic',rows:[[0,6,10],[4,12],[],[0,2,3,6,8,10,11,14],[15],[0,10],[7],[]]}};
$('loadPreset').onclick=()=>{if(project.patterns[selected].some(r=>r.some(Boolean))&&!confirm('Заменить текущий паттерн готовым ритмом?'))return;const p=presets[$('preset').value];project.patterns[selected]=p.rows.map(row=>Array.from({length:16},(_,s)=>row.includes(s)?1:0));project.bpm=p.bpm;project.kit=p.kit;persist();sync();status('Ритм загружен. Нажми «Играть».');};
function saveFile(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('save').onclick=()=>saveFile(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),'ANDATRA-beat.json');$('projectFile').onchange=async()=>{const file=$('projectFile').files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('Проект слишком большой.');const loaded=validateProject(JSON.parse(await file.text()));stop();project=loaded;persist();sync();status('Проект загружен.');}catch(e){status('Не удалось загрузить проект: '+e.message,true);}finally{$('projectFile').value='';}};
async function renderBeat(){const snapshot=validateProject(project),sequence=$('chain').checked?[0,1,2,3]:[selected],repeats=Number($('repeats').value),bar=60/snapshot.bpm*4,duration=bar*sequence.length*repeats;const offline=new OfflineAudioContext(2,Math.ceil((duration+1.5)*44100),44100),out=bus(offline,offline.destination,snapshot.volume);for(let r=0;r<repeats;r++)for(let b=0;b<sequence.length;b++)for(let s=0;s<16;s++){const at=(r*sequence.length+b)*bar+stepTime(s,snapshot.bpm,snapshot.swing);for(let i=0;i<8;i++){const v=snapshot.patterns[sequence[b]][i][s];if(v&&!snapshot.muted[i])trigger(offline,out,i,at,v*snapshot.mix[i],snapshot.kit);}scheduleMelody(offline,out,snapshot.melodies[sequence[b]],r*sequence.length+b,s,at,snapshot.bpm);}return wav(await offline.startRendering());}
async function exportBeat(toStudio=false){if(exporting)return;if(!($('chain').checked?project.patterns:[project.patterns[selected]]).some(p=>p.some((r,i)=>!project.muted[i]&&project.mix[i]>0&&r.some(Boolean)))&&!($("chain").checked?project.melodies:[project.melodies[selected]]).some(m=>m.enabled&&m.volume>0)){status('Добавь ритм или мелодию, прежде чем экспортировать.',true);return;}exporting=true;$('export').disabled=$('studio').disabled=true;status('Собираю WAV…');try{const blob=await renderBeat();if(!toStudio){saveFile(blob,`ANDATRA-beat-${project.bpm}BPM.wav`);status('Бит готов и скачан. Метроном в файл не попадает.');}else{await new Promise((resolve,reject)=>{const r=indexedDB.open('andatra-audio-transfer',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction('files','readwrite');tx.objectStore('files').put({blob,name:`ANDATRA-beat-${project.bpm}BPM.wav`},'beat');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};};});location.href='/studio.html?import=separated';}}catch(e){status('Не удалось собрать бит: '+e.message,true);}finally{exporting=false;$('export').disabled=$('studio').disabled=false;}}
$('export').onclick=()=>exportBeat();$('studio').onclick=()=>exportBeat(true);
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea,[contenteditable=true]'))return;if(e.code==='Space'){e.preventDefault();play();return;}const index=voices.findIndex(v=>'Key'+v[1]===e.code);if(index>=0){e.preventDefault();hit(index);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();status('Воспроизведение остановлено: вкладка скрыта.');}});

const noteNames=['C · До','C♯ · До♯','D · Ре','D♯ · Ре♯','E · Ми','F · Фа','F♯ · Фа♯','G · Соль','G♯ · Соль♯','A · Ля','A♯ · Ля♯','B · Си'];
function option(select,value,title){const o=document.createElement('option');o.value=value;o.textContent=title;select.append(o);}
option($('melodyGenre'),'all','Все стили');genres.forEach(g=>option($('melodyGenre'),g.id,g.name));Object.entries(instruments).forEach(([k,v])=>option($('melodyInstrument'),k,v));noteNames.forEach((n,i)=>option($('melodyRoot'),i,n));
function fillMelodies(wanted){const genre=$('melodyGenre').value,query=$('melodySearch').value.trim().toLowerCase(),items=catalog.filter(p=>(genre==='all'||p.style===genre)&&(`${p.name} ${p.genre}`.toLowerCase().includes(query)));$('melodyPreset').replaceChildren();items.forEach(p=>option($('melodyPreset'),p.id,p.genre+' · '+p.name));if(items.some(p=>p.id===wanted))$('melodyPreset').value=wanted;$('melodyCount').textContent=items.length+' из '+catalog.length;$('melodyPreview').disabled=$('melodyApply').disabled=!items.length;if(!items.length)option($('melodyPreset'),'','Ничего не найдено');}
function controlsMelody(){return melodyConfig({preset:$('melodyPreset').value,enabled:true,root:Number($('melodyRoot').value),octave:Number($('melodyOctave').value),instrument:$('melodyInstrument').value,volume:Number($('melodyVolume').value)/100,bass:$('melodyBass').checked,chords:$('melodyChords').checked});}
function syncMelody(){const m=project.melodies[selected],p=catalog.find(p=>p.id===m.preset);$('melodyGenre').value=m.enabled?p.style:'all';$('melodySearch').value='';fillMelodies(m.preset);$('melodyRoot').value=m.root;$('melodyOctave').value=m.octave;$('melodyInstrument').value=m.instrument;$('melodyVolume').value=m.volume*100;$('melodyVolumeOut').textContent=Math.round(m.volume*100)+'%';$('melodyBass').checked=m.bass;$('melodyChords').checked=m.chords;$('melodyEnabled').checked=m.enabled;melodyInfo();}
function melodyInfo(){const p=catalog.find(p=>p.id===$('melodyPreset').value),m=project.melodies[selected];$('melodyInfo').textContent=p?`${p.genre} · ${p.bpm} BPM · ${p.mode==='major'?'мажор':p.mode==='dorian'?'дорийский лад':p.mode==='phrygian'?'фригийский лад':'минор'} · 4 такта`:'Выбери другой запрос.';$('melodyActive').textContent=m.enabled?`В паттерне ${'ABCD'[selected]}: ${catalog.find(p=>p.id===m.preset).genre} · ${catalog.find(p=>p.id===m.preset).name}`:`В паттерне ${'ABCD'[selected]} мелодия выключена.`;}
function stopPreview(){clearTimeout(previewTimer);previewNodes.forEach(item=>item.nodes.forEach(n=>{try{n.stop?.();}catch{}try{n.disconnect();}catch{}}));previewNodes=[];$('melodyPreview').textContent='▶ Прослушать мелодию';}
$('melodyGenre').onchange=()=>{stopPreview();fillMelodies();chooseSound();};$('melodySearch').oninput=()=>{stopPreview();fillMelodies();melodyInfo();};
function chooseSound(){const p=catalog.find(p=>p.id===$('melodyPreset').value);if(p)$('melodyInstrument').value=p.instrument;melodyInfo();}
$('melodyPreset').onchange=()=>{stopPreview();chooseSound();};
$('melodyPreview').onclick=async()=>{if(previewNodes.length){stopPreview();return;}try{if(playing)stop();await audio();const config=controlsMelody(),bpm=$('melodyTempo').checked?catalog.find(p=>p.id===config.preset).bpm:project.bpm,bar=240/bpm,at=context.currentTime+.03;for(let b=0;b<4;b++)for(let step=0;step<16;step++)previewNodes.push(...scheduleMelody(context,master,config,b,step,at+b*bar+stepTime(step,bpm,project.swing),bpm));$('melodyPreview').textContent='■ Остановить прослушивание';previewTimer=setTimeout(stopPreview,(4*bar+1)*1000);status('Прослушивание выбранной мелодии: 4 такта без ударных.');}catch(e){stopPreview();status('Не удалось прослушать: '+e.message,true);}};
function applyMelody(){if(!$('melodyPreset').value)return;stopPreview();project.melodies[selected]=controlsMelody();if($('melodyTempo').checked){project.bpm=catalog.find(p=>p.id===project.melodies[selected].preset).bpm;$('bpm').value=project.bpm;}persist();$('melodyEnabled').checked=true;melodyInfo();status('Мелодия добавлена в паттерн '+ 'ABCD'[selected]+'. Нажми «Играть»: она звучит вместе с ритмом.');}
$('melodyApply').onclick=applyMelody;
$('melodyRandom').onclick=()=>{const list=[...$('melodyPreset').options].filter(o=>o.value&&o.value!==$('melodyPreset').value);if(!list.length)return;$('melodyPreset').value=list[Math.floor(Math.random()*list.length)].value;chooseSound();applyMelody();};
$('melodyEnabled').onchange=()=>{project.melodies[selected].enabled=$('melodyEnabled').checked;persist();melodyInfo();};
for(const id of ['melodyInstrument','melodyRoot','melodyOctave','melodyVolume','melodyBass','melodyChords'])$(id).addEventListener('input',()=>{stopPreview();$('melodyVolumeOut').textContent=$('melodyVolume').value+'%';if(project.melodies[selected].preset===$('melodyPreset').value){project.melodies[selected]={...controlsMelody(),enabled:$('melodyEnabled').checked};persist();}melodyInfo();});
function frame(){if(playing&&context){const now=context.currentTime,latest=timeline.filter(e=>e.time<=now).at(-1);if(latest){$('position').textContent='ABCD'[latest.pattern]+' · '+String(latest.step+1).padStart(2,'0')+' / 16';if(uiStep!==latest.step){document.querySelectorAll('.step').forEach(e=>e.classList.toggle('current',selected===latest.pattern&&Number(e.dataset.step)===latest.step));uiStep=latest.step;}renderTabs();}}requestAnimationFrame(frame);}sync();frame();

